version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000" # 리액트 포트 매핑
    environment:
      - REACT_APP_API_URL=http://119.202.226.58:8008
    networks:
      - my-network

  backend:
    build:
      context: ./server
    ports:
      - "8008:8008" # 백엔드 포트 매핑
    networks:
      - my-network

  db:
    image: mysql:latest
    ports:
      - "3306:3306" # MySQL 포트 매핑
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todolistdatabase
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
